Repository Judy-999/ios-wanted-BoxOffice, pull requests merged in 2023-01, with the labels that each got.

#2 [Setting] 초기 설정 구현
  BoxOffice.xcodeproj/project.pbxproj
  BoxOffice/Application/AppDelegate.swift
  BoxOffice/Application/SceneDelegate.swift
  BoxOffice/Base.lproj/Main.storyboard
  BoxOffice/Info.plist
  BoxOffice/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  BoxOffice/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  BoxOffice/Resource/Assets.xcassets/Contents.json
  BoxOffice/Resource/Base.lproj/LaunchScreen.storyboard
  BoxOffice/SceneDelegate.swift
  BoxOffice/ViewController.swift
Labels: 설정

#5 [Networking] API 통신 구현 #4
  .gitignore
  APITests/SearchDailyBoxOfficeListAPITests.swift
  APITests/SearchMovieInfoAPITests.swift
  APITests/SearchMoviePosterAPITests.swift
  APITests/SearchWeeklyBoxOfficeListAPITests.swift
  BoxOffice.xcodeproj/project.pbxproj
  BoxOffice/APIs/SearchDailyBoxOfficeListAPI.swift
  BoxOffice/APIs/SearchMovieInfoAPI.swift
  BoxOffice/APIs/SearchMoviePosterAPI.swift
  BoxOffice/APIs/SearchWeeklyBoxOfficeListAPI.swift
  BoxOffice/Model/MovieCellData.swift
  BoxOffice/Model/MovieDetail.swift
  BoxOffice/MovieInfo.plist
  BoxOffice/Network/API.swift
  BoxOffice/Network/APIClient.swift
  BoxOffice/Network/APIConfiguration.swift
  BoxOffice/Network/APIError.swift
  BoxOffice/Network/Bundle+Extension.swift
  BoxOffice/Network/Dictionary+Extension.swift
Labels: 기능

#7 Feature/3 firebase manager
  BoxOffice.xcodeproj/project.pbxproj
  BoxOffice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BoxOffice/Application/AppDelegate.swift
  BoxOffice/Domain/Entities/Review.swift
  BoxOffice/Domain/UseCase/ReviewFirebaseUseCase.swift
  BoxOffice/FirebaseManager/FirebaseError.swift
  BoxOffice/FirebaseManager/FirestoreManager.swift
  BoxOffice/FirebaseManager/StorageManager.swift
  BoxOffice/GoogleService-Info.plist
Labels: 기능

#9 WriteReviewScene
  BoxOffice.xcodeproj/project.pbxproj
  BoxOffice/Domain/Entities/Review.swift
  BoxOffice/Domain/UseCase/ReviewFirebaseUseCase.swift
  BoxOffice/Observable.swift
  BoxOffice/Scene/WriteReviewScene/WriteReviewViewController.swift
  BoxOffice/Scene/WriteReviewScene/WriteReviewViewModel.swift
  BoxOffice/StarRating/StarRatingView.swift
  BoxOffice/StarRating/SubViews/StarImageView.swift
  BoxOffice/StarRating/SubViews/StarRatingUISlider.swift
Labels: 화면, 기능

#11 Feature/6 home view
  BoxOffice.xcodeproj/project.pbxproj
  BoxOffice/APIs/SearchMoviePosterAPI.swift
  BoxOffice/Application/SceneDelegate.swift
  BoxOffice/CalendarModalView/CalendarPresentationController.swift
  BoxOffice/CalendarModalView/CalendarTransitioningDelegate.swift
  BoxOffice/CalendarModalView/CalendarViewController.swift
  BoxOffice/Date+Extension.swift
  BoxOffice/HomeView/GridCell.swift
  BoxOffice/HomeView/HeaderView.swift
  BoxOffice/HomeView/HomeCollectionView.swift
  BoxOffice/HomeView/HomeViewController.swift
  BoxOffice/HomeView/HomeViewModel.swift
  BoxOffice/HomeView/ListCell.swift
  BoxOffice/HomeView/MovieAPIUseCase.swift
  BoxOffice/ImageCacheManager.swift
  BoxOffice/ModeSelectModalView/ModeSelectCell.swift
  BoxOffice/ModeSelectModalView/ModeSelectPresentationController.swift
  BoxOffice/ModeSelectModalView/ModeSelectTransitioningDelegate.swift
  BoxOffice/ModeSelectModalView/ModeSelectViewController.swift
  BoxOffice/Model/MovieCellData.swift
  BoxOffice/Observable.swift
  BoxOffice/ViewController.swift
Labels: 화면, 기능

#12 MovieDetailScene 레이아웃
  BoxOffice.xcodeproj/project.pbxproj
  BoxOffice/Scene/MovieDetailScene/MovieDetailViewController.swift
  BoxOffice/Scene/MovieDetailScene/MovieDetailViewModel.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieLabel.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieMainInfoView.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieReviewView.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieSubInfoView.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/ReviewTableViewCell.swift
  BoxOffice/Scene/WriteReviewScene/MovieReviewViewModel.swift
  BoxOffice/Scene/WriteReviewScene/WriteReviewViewController.swift
  BoxOffice/Scene/WriteReviewScene/WriteReviewViewModel.swift
Labels: 화면

#15 Feature/10 movie detail scene
  BoxOffice/Domain/UseCase/ReviewFirebaseUseCase.swift
  BoxOffice/Scene/HomeScene/HomeViewController.swift
  BoxOffice/Scene/MovieDetailScene/MovieDetailViewController.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieLabel.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieMainInfoView.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieReviewView.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/MovieSubInfoView.swift
  BoxOffice/Scene/MovieDetailScene/SubViews/ReviewTableViewCell.swift
Labels: 화면
